//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Player/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Input"",
            ""id"": ""6e060da3-5afc-43c9-9c63-40586cabe8bd"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""b5207260-afe4-45e7-b296-ca45c1b01966"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""b8e04285-06f1-4404-b18c-5e23c556a0d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""498897fd-d9fc-438e-b605-f8391c352f6c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""37c0908a-6b6c-401b-95d6-b4c8267f3a5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeCamera"",
                    ""type"": ""Button"",
                    ""id"": ""3ff3d9ab-de3d-4ec9-a037-e743a985b518"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActiveSkill"",
                    ""type"": ""Button"",
                    ""id"": ""b1b93da9-b2f9-4e5d-a485-c7e59fa1dfe9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""dd007744-c1d6-4c20-80d8-5f2e31379cfd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""50c4ed3c-e8be-484a-9b7f-ba0dc322160b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation_TopDown"",
                    ""type"": ""Value"",
                    ""id"": ""e9f8912a-622d-48f7-bbac-ee24c2455a5e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation_3rdPerson"",
                    ""type"": ""Value"",
                    ""id"": ""6f20e580-3278-4f51-a2e8-ef747ba3fc49"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotationGamePad"",
                    ""type"": ""Value"",
                    ""id"": ""3477fa7b-b80d-45d4-bc77-d8cedefc18b0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c3cc715d-6ada-461f-9334-a8fb13b9329d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""23dfa9ca-3b68-48d9-9929-91120503c088"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a6014ad4-50be-443c-bee0-0644e34197b6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9718d68a-7dc0-4525-8551-1b426bb9a091"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5c623ed5-cc39-4e69-9f71-e8c7ed6b2bff"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4aa63ec5-f10d-485d-bf14-959361303410"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d9bd1085-c9f1-4a44-bc83-675c622e058e"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19a87221-450d-40ed-9015-719622568e51"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d349c92-26ca-4feb-8a46-11341e784f32"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f516549-55f0-400a-b456-fdc3587e5387"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f2335fd-48f4-49d4-9a2c-fe916d7e42bb"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2cb42f6-483f-4962-8f7f-011597ff5490"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94300e17-b998-4dcc-994d-f870f17b9439"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07001688-b2bd-4df3-9a84-eeaec3a9fa5a"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3eb54a4e-56bf-44a1-8004-a6906e5bdba8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f5f0fe7-63da-43b6-bde9-0dfd85f8953a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4652c3d2-043a-4835-8e7a-e13d45e43c22"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15897c41-7d6e-4832-92ae-8cce49764d04"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43cfd95d-bf48-45c8-a577-feac44eb9baa"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22987c43-5a0a-499e-8070-aea47b75daa0"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8e22ea2-8294-4079-97a1-37849db1e562"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation_3rdPerson"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e257196f-9a68-451c-a53a-c7983425552e"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation_TopDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0235e17-3cc3-42d7-84dc-e49ec3c62e1e"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotationGamePad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Input
        m_Input = asset.FindActionMap("Input", throwIfNotFound: true);
        m_Input_Move = m_Input.FindAction("Move", throwIfNotFound: true);
        m_Input_Run = m_Input.FindAction("Run", throwIfNotFound: true);
        m_Input_Attack = m_Input.FindAction("Attack", throwIfNotFound: true);
        m_Input_ChangeWeapon = m_Input.FindAction("ChangeWeapon", throwIfNotFound: true);
        m_Input_ChangeCamera = m_Input.FindAction("ChangeCamera", throwIfNotFound: true);
        m_Input_ActiveSkill = m_Input.FindAction("ActiveSkill", throwIfNotFound: true);
        m_Input_Interaction = m_Input.FindAction("Interaction", throwIfNotFound: true);
        m_Input_Esc = m_Input.FindAction("Esc", throwIfNotFound: true);
        m_Input_Rotation_TopDown = m_Input.FindAction("Rotation_TopDown", throwIfNotFound: true);
        m_Input_Rotation_3rdPerson = m_Input.FindAction("Rotation_3rdPerson", throwIfNotFound: true);
        m_Input_RotationGamePad = m_Input.FindAction("RotationGamePad", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Input
    private readonly InputActionMap m_Input;
    private IInputActions m_InputActionsCallbackInterface;
    private readonly InputAction m_Input_Move;
    private readonly InputAction m_Input_Run;
    private readonly InputAction m_Input_Attack;
    private readonly InputAction m_Input_ChangeWeapon;
    private readonly InputAction m_Input_ChangeCamera;
    private readonly InputAction m_Input_ActiveSkill;
    private readonly InputAction m_Input_Interaction;
    private readonly InputAction m_Input_Esc;
    private readonly InputAction m_Input_Rotation_TopDown;
    private readonly InputAction m_Input_Rotation_3rdPerson;
    private readonly InputAction m_Input_RotationGamePad;
    public struct InputActions
    {
        private @PlayerInput m_Wrapper;
        public InputActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Input_Move;
        public InputAction @Run => m_Wrapper.m_Input_Run;
        public InputAction @Attack => m_Wrapper.m_Input_Attack;
        public InputAction @ChangeWeapon => m_Wrapper.m_Input_ChangeWeapon;
        public InputAction @ChangeCamera => m_Wrapper.m_Input_ChangeCamera;
        public InputAction @ActiveSkill => m_Wrapper.m_Input_ActiveSkill;
        public InputAction @Interaction => m_Wrapper.m_Input_Interaction;
        public InputAction @Esc => m_Wrapper.m_Input_Esc;
        public InputAction @Rotation_TopDown => m_Wrapper.m_Input_Rotation_TopDown;
        public InputAction @Rotation_3rdPerson => m_Wrapper.m_Input_Rotation_3rdPerson;
        public InputAction @RotationGamePad => m_Wrapper.m_Input_RotationGamePad;
        public InputActionMap Get() { return m_Wrapper.m_Input; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputActions set) { return set.Get(); }
        public void SetCallbacks(IInputActions instance)
        {
            if (m_Wrapper.m_InputActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_InputActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnMove;
                @Run.started -= m_Wrapper.m_InputActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnRun;
                @Attack.started -= m_Wrapper.m_InputActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnAttack;
                @ChangeWeapon.started -= m_Wrapper.m_InputActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnChangeWeapon;
                @ChangeCamera.started -= m_Wrapper.m_InputActionsCallbackInterface.OnChangeCamera;
                @ChangeCamera.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnChangeCamera;
                @ChangeCamera.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnChangeCamera;
                @ActiveSkill.started -= m_Wrapper.m_InputActionsCallbackInterface.OnActiveSkill;
                @ActiveSkill.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnActiveSkill;
                @ActiveSkill.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnActiveSkill;
                @Interaction.started -= m_Wrapper.m_InputActionsCallbackInterface.OnInteraction;
                @Interaction.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnInteraction;
                @Interaction.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnInteraction;
                @Esc.started -= m_Wrapper.m_InputActionsCallbackInterface.OnEsc;
                @Esc.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnEsc;
                @Esc.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnEsc;
                @Rotation_TopDown.started -= m_Wrapper.m_InputActionsCallbackInterface.OnRotation_TopDown;
                @Rotation_TopDown.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnRotation_TopDown;
                @Rotation_TopDown.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnRotation_TopDown;
                @Rotation_3rdPerson.started -= m_Wrapper.m_InputActionsCallbackInterface.OnRotation_3rdPerson;
                @Rotation_3rdPerson.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnRotation_3rdPerson;
                @Rotation_3rdPerson.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnRotation_3rdPerson;
                @RotationGamePad.started -= m_Wrapper.m_InputActionsCallbackInterface.OnRotationGamePad;
                @RotationGamePad.performed -= m_Wrapper.m_InputActionsCallbackInterface.OnRotationGamePad;
                @RotationGamePad.canceled -= m_Wrapper.m_InputActionsCallbackInterface.OnRotationGamePad;
            }
            m_Wrapper.m_InputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @ChangeWeapon.started += instance.OnChangeWeapon;
                @ChangeWeapon.performed += instance.OnChangeWeapon;
                @ChangeWeapon.canceled += instance.OnChangeWeapon;
                @ChangeCamera.started += instance.OnChangeCamera;
                @ChangeCamera.performed += instance.OnChangeCamera;
                @ChangeCamera.canceled += instance.OnChangeCamera;
                @ActiveSkill.started += instance.OnActiveSkill;
                @ActiveSkill.performed += instance.OnActiveSkill;
                @ActiveSkill.canceled += instance.OnActiveSkill;
                @Interaction.started += instance.OnInteraction;
                @Interaction.performed += instance.OnInteraction;
                @Interaction.canceled += instance.OnInteraction;
                @Esc.started += instance.OnEsc;
                @Esc.performed += instance.OnEsc;
                @Esc.canceled += instance.OnEsc;
                @Rotation_TopDown.started += instance.OnRotation_TopDown;
                @Rotation_TopDown.performed += instance.OnRotation_TopDown;
                @Rotation_TopDown.canceled += instance.OnRotation_TopDown;
                @Rotation_3rdPerson.started += instance.OnRotation_3rdPerson;
                @Rotation_3rdPerson.performed += instance.OnRotation_3rdPerson;
                @Rotation_3rdPerson.canceled += instance.OnRotation_3rdPerson;
                @RotationGamePad.started += instance.OnRotationGamePad;
                @RotationGamePad.performed += instance.OnRotationGamePad;
                @RotationGamePad.canceled += instance.OnRotationGamePad;
            }
        }
    }
    public InputActions @Input => new InputActions(this);
    public interface IInputActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnChangeWeapon(InputAction.CallbackContext context);
        void OnChangeCamera(InputAction.CallbackContext context);
        void OnActiveSkill(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnEsc(InputAction.CallbackContext context);
        void OnRotation_TopDown(InputAction.CallbackContext context);
        void OnRotation_3rdPerson(InputAction.CallbackContext context);
        void OnRotationGamePad(InputAction.CallbackContext context);
    }
}
